#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
##SBATCH --reservation=cbmucl
#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# joining paired ends
echo "joining paired ends"
time join_paired_ends.py -f Read1.fastq -r Read2.fastq -b Index.fastq -o Read1Read2_paired -m fastq-join
source deactivate
