#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
##SBATCH --reservation=cbmucl
#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
echo "performing Procrustes"
time transform_coordinate_matrices.py -i cdoutGG_HPC_nocompare_35000/bdiv_even35000/unweighted_unifrac_pc.txt,cdoutGG_HPC_nocompare_35000/bdiv_even35000/weighted_unifrac_pc.txt -o Stats/Procrustes -r 999
source deactivate
