#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
##SBATCH --reservation=cbmucl
#Load modules
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# splitting libraries
echo "splitting libraries"
time split_libraries_fastq.py -m map_incomplete.tsv -i ./Read1Read2_paired/fastqjoin.join.fastq -b ./Read1Read2_paired/fastqjoin.join_barcodes.fastq -o ./slout_JoinedReads -q 19 -r 3 --rev_comp_barcode --rev_comp_mapping_barcodes
# counting sequences
echo "Counting sequences"
time count_seqs.py -i slout_JoinedReads/seqs.fna
# deactivating environment
source deactivate
